### ISSUE TITLE
Horizontal date selector

### ISSUE THREAD

**Issue by priyesh9875** [Onefootball/onefootball-angular-components#22]
Can we have following component included in this repo

![screenshot from 2018-03-29 23-05-22](https://user-images.githubusercontent.com/19514760/38104102-d92d7c82-33a5-11e8-9a9d-70e06d44822c.png)

**Comment by NKjoep** [comment]
Hello, thank you for your interest in our project.
Unfortunately, we cannot do that for few reasons. 

This project was meant to provide generic tools (filters, directives, ...) to support developers in building final component/pages. 

And in addition to this, the component you took a screenshot of is based on our new website and it is powered by Angular > 2.
