### ISSUE TITLE
Notification not opening the app

### ISSUE THREAD

**Issue by hemanthkotaprolu** [Onefootball/onefootball-angular-components#32]
When i click on the notification in my android mobile. The app is not starting. But when the application is on then the notification is opening.

**Comment by NKjoep** [comment]
hi @hemanthkotaprolu! 

sorry for the late reply, your message got lost in my inbox. 
If you still have an issue with the OneFootball mobile app, please reach out to our customer support team
[feedback@onefootball.com](mailto:feedback@onefootball.com) 

We'll be happy to help you with anything.
